spring.application.name=Project

server.port=8080
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://localhost:5432/feedback_db
spring.datasource.username=feedback_user
spring.datasource.password=feedback_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=INFO
logging.level.com.ssatr.Project=DEBUG

# JWT
app.jwt.secret=super_long_random_secret_key_minimum_64_characters_123456789
app.jwt.accessMinutes=60
app.jwt.qrTokenMinutes=30

# QR opens frontend participant page (not backend submit)
app.publicSubmitUrl=http://localhost:4200/participant?token=

logging.level.org.springframework.security=DEBUG
logging.level.com.ssatr.Project.security=DEBUG

